name: Deploy projects to Contember Cloud

on:
  push:
    branches:
      - 'deploy/beta'
      - 'deploy/prod'

jobs:
  deploy:
    if: github.repository == 'manGoweb/ukrajina-contember'
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Detect Stage        # refs/heads/deploy/beta -> beta
        run: 'echo "STAGE=${GITHUB_REF: -4}" >> $GITHUB_ENV'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Validate Schema
        uses: docker://contember/cli:1.1
        with:
          args: project:validate .

      - name: Deploy Beta
        if: ${{ env.STAGE == 'beta' }}
        env:
          NODE_ENV: production
          VITE_USER_NODE_ENV: production
          VITE_CONTEMBER_ADMIN_SENTRY_DSN: ${{ secrets.ADMIN_SENTRY_DSN }}
        run: npm run -- deploy ${{ secrets.CLOUD_BETA_DSN }} --yes

      - name: Deploy Prod
        if: ${{ env.STAGE == 'prod' }}
        env:
          NODE_ENV: production
          VITE_USER_NODE_ENV: production
          VITE_CONTEMBER_ADMIN_SENTRY_DSN: ${{ secrets.ADMIN_SENTRY_DSN }}
        run: npm run -- deploy ${{ secrets.CLOUD_PROD_DSN }} --yes
